### ISSUE TITLE
webkit nvidia support (branch main)

### ISSUE THREAD

**Issue by pissard** [braillerap/DesktopBrailleRAP#2]
With a ubuntu 22.04 and a NVIDIA driver when the app can not be displayed with an error message:

KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission non accordée
Failed to create GBM buffer of size 800x600: Permission non accordée

**Comment by pissard** [comment]
you can disable the buffer with the environment variable:

export WEBKIT_DISABLE_DMABUF_RENDERER=1

**Comment by crocsg** [comment]
> GBM buffer of size 800x600: Permission non accordée

I don't have the hardrware to test it. What would be the best place to do that ?
- in desktopbraillerap.py (even if you don't have an NVIDIA graphic card)

I just see Ubuntu 22.04 and i only provide binary for ubuntu 24.04, would it be usefull to have ubuntu 22.04 prebuld binaries ?

**Comment by pissard** [comment]
I do not have an idea how to do that properly. I need to investigate the webkit lib.

**Comment by pissard** [comment]
you can close this issue, solved with issue #4
