### ISSUE TITLE
Not possible to Print graph + text/braille on Ubuntu (branch main)

### ISSUE THREAD

**Issue by pissard** [braillerap/DesktopBrailleRAP#4]
With an ubuntu version is not possible to 'Print' a graph with a text to be translate in braille.
The app freezes.

**Comment by crocsg** [comment]
Hello Roger
just tried main head with Debian 12 on laptop and Ubuntu 24 in VM. Printed a mix of 2 svg and text label. Everything is fine. This issue need more investigation for proper diagnostic. Can you attach your svg test file ?

**Comment by pissard** [comment]
Hello stephane,

It is due to an  incorrect installation from my part on my ubuntu 22.04. For now,  I need to investigate and understand why. Using the repo braillerap/BuildDesktopBrailleRAPLinux#, i build a correct app for ubuntu 22.04.

**Comment by pissard** [comment]
I can be more specific. On my desktop ubuntu 22.04, when I use the  app build by 'npm run buildubuntu' (./dist/desktopbraillerap-ubuntu) it is ok. When I use 'npm run startview', I have this bug.

**Comment by crocsg** [comment]
Maybe this is because when you use "npm run startview" we try to start the app in GTK mode, not QT, just because debug windows is not available in QT. can you try changing line 481 of desktopbraillerap.py, replace "GTK" by "QT"

**Comment by pissard** [comment]
Replacing the "GTK" by "QT" solves this issue. It solves also the issue #2 

I was going around, thank you for your valuable advice. I'm sorry I'm not very efficient, but I'm getting into the code slowly...
