### ISSUE TITLE
add functionnality: embossing height

### ISSUE THREAD

**Issue by pissard** [braillerap/DesktopBrailleRAP#6]
To clarify complex designs, it would be useful to be able to control the height of the embossing. Line color could give an indication of embossing height, for example.

**Comment by pissard** [comment]
stroke-opacity is maybe a better choice than color ?

**Comment by crocsg** [comment]
This feature need to be implemented on BrailleRAP device. Somewhat started feature in Marlin2 
[https://github.com/braillerap/MarlinBraille2](https://github.com/braillerap/MarlinBraille2)
file Marlin\src\gcode\control\M3-M5.cpp line 164
