### ISSUE TITLE
add functionnality:  filling shapes with "embossing points texture"

### ISSUE THREAD

**Issue by pissard** [braillerap/DesktopBrailleRAP#8]
to clarify complex designs, it would be useful to be able to control the filling of shapes with embossing points texture.
The color fill could give an indication of this texture for example

**Comment by crocsg** [comment]
Filling shapes with pattern is a feature coming in the next release. But we also have to evaluate what is a "good" texture

**Comment by crocsg** [comment]
Filling shape based on filling colors is available in branch "pattern" with several patterns proposed. Will be merged in main after some field tests.
